/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.udec.vista;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Oscar
 */
public class Bancos extends JInternalFrame {
    
    public Bancos() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("com.udec_nomina_jar_1.0-SNAPSHOTPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Banco b");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell

            }};
            codigoLabel = new javax.swing.JLabel();
            bancoLabel = new javax.swing.JLabel();
            codigoField = new javax.swing.JTextField();
            bancoField = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            newButton1 = new javax.swing.JButton();
            refreshButton1 = new javax.swing.JButton();
            saveButton1 = new javax.swing.JButton();

            FormListener formListener = new FormListener();

            org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
            org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
            columnBinding.setColumnName("Codigo");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${banco}"));
            columnBinding.setColumnName("Banco");
            columnBinding.setColumnClass(String.class);
            bindingGroup.addBinding(jTableBinding);
            jTableBinding.bind();
            masterScrollPane.setViewportView(masterTable);

            codigoLabel.setText("Codigo:");

            bancoLabel.setText("Banco:");

            codigoField.setToolTipText("");

            org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigo}"), codigoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codigoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            bancoField.setToolTipText("");

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.banco}"), bancoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), bancoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            bancoField.addActionListener(formListener);

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            jLabel1.setText("Listado de bancos");

            newButton1.setIcon(new javax.swing.ImageIcon("img/nuevo2.png"));
            newButton1.setText("Nuevo");
            newButton1.setBorder(null);
            newButton1.setBorderPainted(false);
            newButton1.setContentAreaFilled(false);
            newButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            newButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            newButton1.setIconTextGap(-3);
            newButton1.setMaximumSize(new java.awt.Dimension(115, 100));
            newButton1.setMinimumSize(new java.awt.Dimension(115, 100));
            newButton1.setPreferredSize(new java.awt.Dimension(115, 100));
            newButton1.setPressedIcon(new javax.swing.ImageIcon("img/nuevo33.png"));
            newButton1.setRolloverIcon(new javax.swing.ImageIcon("img/nuevo1.png"));
            newButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            newButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            newButton1.addActionListener(formListener);

            refreshButton1.setIcon(new javax.swing.ImageIcon("img/refres2.png"));
            refreshButton1.setText("Actualizar");
            refreshButton1.setBorder(null);
            refreshButton1.setBorderPainted(false);
            refreshButton1.setContentAreaFilled(false);
            refreshButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            refreshButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            refreshButton1.setIconTextGap(-3);
            refreshButton1.setPressedIcon(new javax.swing.ImageIcon("img/refresh3.png"));
            refreshButton1.setRolloverIcon(new javax.swing.ImageIcon("img/refresh1.png"));
            refreshButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            refreshButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            refreshButton1.addActionListener(formListener);

            saveButton1.setIcon(new javax.swing.ImageIcon("img/guardar2.png"));
            saveButton1.setText("Guardar Cambios");
            saveButton1.setBorder(null);
            saveButton1.setBorderPainted(false);
            saveButton1.setContentAreaFilled(false);
            saveButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            saveButton1.setIconTextGap(-3);
            saveButton1.setPressedIcon(new javax.swing.ImageIcon("img/guardar33.png"));
            saveButton1.setRolloverIcon(new javax.swing.ImageIcon("img/guardar1.png"));
            saveButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            saveButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            saveButton1.addActionListener(formListener);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codigoLabel)
                                .addComponent(bancoLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codigoField)
                                .addComponent(bancoField)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(newButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(refreshButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoLabel)
                        .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bancoLabel)
                        .addComponent(bancoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(48, Short.MAX_VALUE))
            );

            bindingGroup.bind();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener {
            FormListener() {}
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (evt.getSource() == bancoField) {
                    Bancos.this.bancoFieldActionPerformed(evt);
                }
                else if (evt.getSource() == newButton1) {
                    Bancos.this.newButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == refreshButton1) {
                    Bancos.this.refreshButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == saveButton1) {
                    Bancos.this.saveButton1ActionPerformed(evt);
                }
            }
        }// </editor-fold>//GEN-END:initComponents

    

   
    private void bancoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bancoFieldActionPerformed

    private void newButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton1ActionPerformed
        com.udec.modelo.Banco b = new com.udec.modelo.Banco();
        entityManager.persist(b);
        list.add(b);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButton1ActionPerformed

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButton1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<com.udec.modelo.Banco> merged = new ArrayList<com.udec.modelo.Banco>(list.size());
            for (com.udec.modelo.Banco b : list) {
                merged.add(entityManager.merge(b));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bancoField;
    private javax.swing.JLabel bancoLabel;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private java.util.List<com.udec.modelo.Banco> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton1;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JButton saveButton1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
  
    
}
