/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udec.vista;

import com.udec.controlador.ConceptoJpaController;
import com.udec.controlador.DiastrabajadosJpaController;
import com.udec.controlador.EmpleadoJpaController;
import com.udec.controlador.NominaJpaController;
import com.udec.controlador.NovedadmedicJpaController;
import com.udec.controlador.NovedadxconceptoJpaController;
import com.udec.controlador.ParametrosGeneralesJpaController;
import com.udec.controlador.exceptions.NonexistentEntityException;
import com.udec.modelo.Diastrabajados;
import com.udec.modelo.Empleado;
import com.udec.modelo.Nomina;
import com.udec.modelo.Novedadmedic;
import com.udec.modelo.Novedadxconcepto;
import com.udec.modelo.Periodo;
import java.awt.Component;
import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.RollbackException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Ususario
 */
public class DiasTrabajados extends JInternalFrame {

    private Periodo p;

    public DiasTrabajados(Periodo pe) {
        this.p = pe;
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("com.udec_nomina_jar_1.0-SNAPSHOTPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM Diastrabajados d");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        empleadoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Empleado e");
        empleadoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : empleadoQuery.getResultList();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable(){
            public void changeSelection(final int row, final int column, boolean toggle, boolean extend)
            {
                super.changeSelection(row, column, toggle, extend);
                if(column==1){
                    masterTable.editCellAt(row, column);
                    masterTable.transferFocus();
                    Component editor = getEditorComponent();
                    editor.requestFocusInWindow();
                    ((JTextComponent)editor).selectAll();
                }

            }
        };
        empleadoCodigoLabel = new javax.swing.JLabel();
        diasLabel = new javax.swing.JLabel();
        diasField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${empleadoCodigo.nombre}"));
        columnBinding.setColumnName("Empleado");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dias}"));
        columnBinding.setColumnName("Dias trabajados");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        empleadoCodigoLabel.setText("Empleado:");

        diasLabel.setText("Dias trabajados:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dias}"), diasField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), diasField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveButton.setText("Guardar Cambios");
        saveButton.addActionListener(formListener);

        refreshButton.setText("Actualizar");
        refreshButton.addActionListener(formListener);

        jComboBox1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Empleado) {
                    Empleado mec = (Empleado)value;
                    setText(mec.getNombre());
                }
                return this;
            }
        });

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, empleadoList, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.empleadoCodigo}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jButton1.setText("Liquidar nomina");
        jButton1.addActionListener(formListener);

        jButton2.setText("Recalcular empleados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoCodigoLabel)
                            .addComponent(diasLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diasField, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {refreshButton, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoCodigoLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasLabel)
                    .addComponent(diasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(saveButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                DiasTrabajados.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                DiasTrabajados.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                DiasTrabajados.this.jButton1ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<com.udec.modelo.Diastrabajados> merged = new ArrayList<com.udec.modelo.Diastrabajados>(list.size());
            for (com.udec.modelo.Diastrabajados d : list) {
                merged.add(entityManager.merge(d));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NominaJpaController nC = new NominaJpaController();
        EmpleadoJpaController eC = new EmpleadoJpaController();
        ConceptoJpaController cC = new ConceptoJpaController();
        NovedadmedicJpaController nmC = new NovedadmedicJpaController();
        NovedadxconceptoJpaController ncC = new NovedadxconceptoJpaController();
        ParametrosGeneralesJpaController pgC = new ParametrosGeneralesJpaController();
        DiastrabajadosJpaController dtC = new DiastrabajadosJpaController();
        List<Nomina> nominas = nC.findByList("periodoIdperiodo", p);
        List<Empleado> empleadosActivos = eC.findByList("estado", "ACTIVO");
        for (Nomina nomina : nominas) {
            try {
                nC.destroy(nomina.getIdnomina());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(DiasTrabajados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        com.udec.modelo.ParametrosGenerales pg = pgC.findParametrosGenerales(1);

        for (Empleado empleado : empleadosActivos) {
            Nomina aux = new Nomina();
            aux.setEmpleadoCodigo(empleado); //empleado
            aux.setConceptoIdconcepto(cC.findConcepto(1)); //sueldo
            aux.setPeriodoIdperiodo(p);
            Diastrabajados dt = dtC.findBySingle2("empleadoCodigo", empleado, "periodoIdperiodo", p);
            Double sueldoQuincena = (Double) empleado.getSalario() * dt.getDias()/30;
            aux.setValor(sueldoQuincena); //sueldo Quincena
            nC.create(aux);

            //subsidio de transporte
            if ((empleado.getSalario() < (double) (pg.getSalarioMinimo() * 2)) && empleado.getTipo().equals("PLANTA")) { //si el salario no supera los 2 SMLV y el empleado es de planta
                Nomina aux2 = new Nomina();
                aux2.setEmpleadoCodigo(empleado); //empleado
                aux2.setConceptoIdconcepto(cC.findConcepto(2)); //auxilio de transporte
                aux2.setPeriodoIdperiodo(p); //periodo
                Double subsidioT = (double) (dt.getDias() * pg.getSubsidioTransporte() / 30);
                aux2.setValor(subsidioT); //subsidio de transporte
                nC.create(aux2);
            }

            //subsidio de alimentacion
            if ((empleado.getSalario() < (double) 1228170) && empleado.getTipo().equals("PLANTA")) { //si el salario no supera 1.228.170 y el empleado es de planta
                Nomina aux3 = new Nomina();
                aux3.setEmpleadoCodigo(empleado); //empleado
                aux3.setConceptoIdconcepto(cC.findConcepto(3)); //auxilio de alimentacion
                aux3.setPeriodoIdperiodo(p); //periodo
                Double subsidioA = (double) (dt.getDias() * pg.getSubsidioAlimentacion() / 30);
                aux3.setValor(subsidioA); //subsidio de alimentacion
                nC.create(aux3);
            }

            //algun concepto de devengado en novedades por concepto
            List<Novedadxconcepto> nc = ncC.findByList3("empleadoCodigo", empleado, "conceptoIdconcepto.tipo", "DEVENGADO", p);
            for (Novedadxconcepto novedadxconcepto : nc) {
                Nomina aux4 = new Nomina();
                aux4.setEmpleadoCodigo(empleado); //empleado
                aux4.setConceptoIdconcepto(novedadxconcepto.getConceptoIdconcepto()); //concepto de algo devengado
                aux4.setPeriodoIdperiodo(p); //periodo
                aux4.setValor(novedadxconcepto.getValor()); //valor a pagar en el concepto
                nC.create(aux4);
            }

            //incapacidad de origen comun
            List<Novedadmedic> novedadesMedicasOrigenComun = nmC.findByPeriodoEmpleadoO(p, empleado, "Incapacidad de origen común");
            if (!novedadesMedicasOrigenComun.isEmpty()) {
                Nomina aux3 = new Nomina();
                aux3.setEmpleadoCodigo(empleado); //empleado
                aux3.setConceptoIdconcepto(cC.findConcepto(4)); //INCAPACIDAD DE ORIGEN COMUN
                aux3.setPeriodoIdperiodo(p); //periodo
                Double valorIncapacidad = 0.0;
                for (Novedadmedic novedadmedic : novedadesMedicasOrigenComun) {
                    if (novedadmedic.getFechaInicio().before(p.getDesde()) && novedadmedic.getFechaFinal().after(p.getHasta())) { //si la incapacidad comienza antes del periodo y se acaba despues del periodo

                    } else {
                        if (novedadmedic.getFechaInicio().before(p.getDesde()) && !novedadmedic.getFechaFinal().after(p.getHasta())) { //si la incapacidad comienza antes del periodo y se acaba dentro del periodo

                        } else {
                            if (!novedadmedic.getFechaInicio().before(p.getDesde()) && novedadmedic.getFechaFinal().after(p.getHasta())) { //si la incapacidad comienza dentro del periodo y se acaba despues del periodo

                            } else {
                                if (!novedadmedic.getFechaInicio().before(p.getDesde()) && !novedadmedic.getFechaFinal().after(p.getHasta())) { //si la incapacidad esta dentro del periodo

                                }
                            }
                        }
                    }
                }
            }

            //DEDUCCIONES
            //Seguridad Social
            Nomina aux5 = new Nomina();
            aux5.setEmpleadoCodigo(empleado); //empleado
            aux5.setConceptoIdconcepto(cC.findConcepto(14)); //SALUD
            aux5.setPeriodoIdperiodo(p); //periodo
            aux5.setValor(sueldoQuincena * pg.getPorcentajeSalud() / 100); //valor Salud
            nC.create(aux5);

            //Pension
            Nomina aux6 = new Nomina();
            aux6.setEmpleadoCodigo(empleado); //empleado
            aux6.setConceptoIdconcepto(cC.findConcepto(15)); //PENSION
            aux6.setPeriodoIdperiodo(p); //periodo
            aux6.setValor(sueldoQuincena * pg.getPorcentajePension() / 100); //valor Pension
            nC.create(aux6);

            //FSP
            if (empleado.getSalario() >= (double)(pg.getSalarioMinimo()*4)) {
                Nomina aux7 = new Nomina();
                aux7.setEmpleadoCodigo(empleado); //empleado
                aux7.setConceptoIdconcepto(cC.findConcepto(16)); //FSP
                aux7.setPeriodoIdperiodo(p); //periodo
                aux7.setValor(sueldoQuincena * pg.getPorcentajeFps() / 100); //valor FSP
                nC.create(aux7);
            }
            
            
            //OTRAS DEDUCCIONES
            List<Novedadxconcepto> nc2 = ncC.findByList4("empleadoCodigo", empleado, "conceptoIdconcepto.tipo", "DEDUCIDO", p);
            for (Novedadxconcepto novedadxconcepto : nc2) {
                Nomina aux8 = new Nomina();
                aux8.setEmpleadoCodigo(empleado); //empleado
                aux8.setConceptoIdconcepto(novedadxconcepto.getConceptoIdconcepto()); //concepto de algo devengado
                aux8.setPeriodoIdperiodo(p); //periodo
                aux8.setValor(novedadxconcepto.getValor()); //valor a pagar en el concepto
                nC.create(aux8);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diasField;
    private javax.swing.JLabel diasLabel;
    private javax.swing.JLabel empleadoCodigoLabel;
    private java.util.List<com.udec.modelo.Empleado> empleadoList;
    private javax.persistence.Query empleadoQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private java.util.List<com.udec.modelo.Diastrabajados> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
