/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.udec.vista;

import com.udec.modelo.Banco;
import com.udec.modelo.Cargo;
import com.udec.modelo.Empleado;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Font;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JList;


/**
 *
 * @author Oscar
 */
public class Empleados2 extends JInternalFrame {
    
    public Empleados2() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("com.udec_nomina_jar_1.0-SNAPSHOTPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Empleado e ORDER BY e.nombre");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        bancoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Banco b");
        bancoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bancoQuery.getResultList();
        cargoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cargo c");
        cargoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cargoQuery.getResultList();
        empleadoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Empleado e");
        empleadoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : empleadoQuery.getResultList();
        dateConverter1 = new com.udec.vista.DateConverter();
        doubleConverter1 = new com.udec.vista.DoubleConverter();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell

            }};
            codigoLabel = new javax.swing.JLabel();
            cedulaLabel = new javax.swing.JLabel();
            nombreLabel = new javax.swing.JLabel();
            salarioLabel = new javax.swing.JLabel();
            tipoLabel = new javax.swing.JLabel();
            estadoLabel = new javax.swing.JLabel();
            bancoIdbancoLabel = new javax.swing.JLabel();
            numeroCuentaLabel = new javax.swing.JLabel();
            cargoCargoidLabel = new javax.swing.JLabel();
            codigoField = new javax.swing.JTextField();
            cedulaField = new javax.swing.JTextField();
            nombreField = new javax.swing.JTextField();
            salarioField = new javax.swing.JTextField();
            numeroCuentaField = new javax.swing.JTextField();
            jComboBox1 = new javax.swing.JComboBox();
            jComboBox2 = new javax.swing.JComboBox();
            jComboBox3 = new javax.swing.JComboBox();
            jComboBox4 = new javax.swing.JComboBox();
            newButton1 = new javax.swing.JButton();
            refreshButton1 = new javax.swing.JButton();
            saveButton1 = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();

            FormListener formListener = new FormListener();

            setTitle("Listado de empleados");
            setToolTipText("");
            setPreferredSize(new java.awt.Dimension(1178, 440));

            org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
            org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
            columnBinding.setColumnName("Codigo");
            columnBinding.setColumnClass(Integer.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cedula}"));
            columnBinding.setColumnName("Cedula");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
            columnBinding.setColumnName("Nombre");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${salario}"));
            columnBinding.setColumnName("Salario");
            columnBinding.setColumnClass(Double.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipo}"));
            columnBinding.setColumnName("Tipo de contrato");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
            columnBinding.setColumnName("Estado");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bancoIdbanco.banco}"));
            columnBinding.setColumnName("Banco");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroCuenta}"));
            columnBinding.setColumnName("Numero Cuenta");
            columnBinding.setColumnClass(String.class);
            columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cargoCargoid.cargo}"));
            columnBinding.setColumnName("Cargo");
            columnBinding.setColumnClass(String.class);
            bindingGroup.addBinding(jTableBinding);
            jTableBinding.bind();
            masterTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(1).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            masterTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(4).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(5).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(6).setPreferredWidth(150);
            masterTable.getColumnModel().getColumn(7).setPreferredWidth(75);
            masterTable.getColumnModel().getColumn(8).setPreferredWidth(250);
            masterScrollPane.setViewportView(masterTable);
            if (masterTable.getColumnModel().getColumnCount() > 0) {
                masterTable.getColumnModel().getColumn(8).setResizable(false);
            }

            codigoLabel.setText("Codigo:");

            cedulaLabel.setText("Cedula:");

            nombreLabel.setText("Nombre:");

            salarioLabel.setText("Salario:");

            tipoLabel.setText("Tipo de contrato:");

            estadoLabel.setText("Estado:");

            bancoIdbancoLabel.setText("Banco:");

            numeroCuentaLabel.setText("Numero Cuenta:");

            cargoCargoidLabel.setText("Cargo:");

            org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigo}"), codigoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codigoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cedula}"), cedulaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), cedulaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nombre}"), nombreField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nombreField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.salario}"), salarioField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            binding.setConverter(doubleConverter1);
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), salarioField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numeroCuenta}"), numeroCuentaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
            binding.setSourceUnreadableValue("");
            bindingGroup.addBinding(binding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), numeroCuentaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
            bindingGroup.addBinding(binding);

            jComboBox1.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(
                    JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof Banco) {
                        Banco mec = (Banco)value;
                        setText(mec.getBanco());
                    }
                    return this;
                }
            });

            org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bancoList, jComboBox1);
            bindingGroup.addBinding(jComboBoxBinding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.bancoIdbanco}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
            bindingGroup.addBinding(binding);

            jComboBox2.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(
                    JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof Cargo) {
                        Cargo mec = (Cargo)value;
                        setText(mec.getCargo());
                    }
                    return this;
                }
            });

            jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cargoList, jComboBox2);
            bindingGroup.addBinding(jComboBoxBinding);
            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cargoCargoid}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
            bindingGroup.addBinding(binding);

            jComboBox2.addActionListener(formListener);

            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PLANTA", "CONTRATO" }));

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tipo}"), jComboBox3, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
            bindingGroup.addBinding(binding);

            jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "INACTIVO" }));
            jComboBox4.setMaximumSize(new java.awt.Dimension(170, 20));
            jComboBox4.setMinimumSize(new java.awt.Dimension(106, 20));
            jComboBox4.setPreferredSize(new java.awt.Dimension(106, 20));

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.estado}"), jComboBox4, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
            bindingGroup.addBinding(binding);

            newButton1.setIcon(new javax.swing.ImageIcon("img/nuevo2.png"));
            newButton1.setText("Nuevo");
            newButton1.setBorder(null);
            newButton1.setBorderPainted(false);
            newButton1.setContentAreaFilled(false);
            newButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            newButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            newButton1.setIconTextGap(-3);
            newButton1.setMaximumSize(new java.awt.Dimension(115, 100));
            newButton1.setMinimumSize(new java.awt.Dimension(115, 100));
            newButton1.setPreferredSize(new java.awt.Dimension(115, 100));
            newButton1.setPressedIcon(new javax.swing.ImageIcon("img/nuevo33.png"));
            newButton1.setRolloverIcon(new javax.swing.ImageIcon("img/nuevo1.png"));
            newButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            newButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            newButton1.addActionListener(formListener);

            refreshButton1.setIcon(new javax.swing.ImageIcon("img/refres2.png"));
            refreshButton1.setText("Actualizar");
            refreshButton1.setBorder(null);
            refreshButton1.setBorderPainted(false);
            refreshButton1.setContentAreaFilled(false);
            refreshButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            refreshButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            refreshButton1.setIconTextGap(-3);
            refreshButton1.setPressedIcon(new javax.swing.ImageIcon("img/refresh3.png"));
            refreshButton1.setRolloverIcon(new javax.swing.ImageIcon("img/refresh1.png"));
            refreshButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            refreshButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            refreshButton1.addActionListener(formListener);

            saveButton1.setIcon(new javax.swing.ImageIcon("img/guardar2.png"));
            saveButton1.setText("Guardar Cambios");
            saveButton1.setBorder(null);
            saveButton1.setBorderPainted(false);
            saveButton1.setContentAreaFilled(false);
            saveButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            saveButton1.setIconTextGap(-3);
            saveButton1.setPressedIcon(new javax.swing.ImageIcon("img/guardar33.png"));
            saveButton1.setRolloverIcon(new javax.swing.ImageIcon("img/guardar1.png"));
            saveButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            saveButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            saveButton1.addActionListener(formListener);

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            jLabel1.setText("Listado de empleados");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(masterScrollPane))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bancoIdbancoLabel)
                                .addComponent(cargoCargoidLabel)
                                .addComponent(nombreLabel)
                                .addComponent(codigoLabel))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cedulaLabel)
                                .addComponent(tipoLabel)
                                .addComponent(salarioLabel)
                                .addComponent(numeroCuentaLabel)
                                .addComponent(estadoLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeroCuentaField)
                                .addComponent(jComboBox4, 0, 427, Short.MAX_VALUE)
                                .addComponent(salarioField)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cedulaField)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(newButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(refreshButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );

            layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {codigoField, jComboBox1, jComboBox2, nombreField});

            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoLabel)
                        .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cedulaLabel)
                        .addComponent(cedulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreLabel)
                        .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoLabel)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cargoCargoidLabel)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salarioLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bancoIdbancoLabel)
                        .addComponent(numeroCuentaLabel)
                        .addComponent(numeroCuentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoLabel))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            bindingGroup.bind();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener {
            FormListener() {}
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (evt.getSource() == jComboBox2) {
                    Empleados2.this.jComboBox2ActionPerformed(evt);
                }
                else if (evt.getSource() == newButton1) {
                    Empleados2.this.newButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == refreshButton1) {
                    Empleados2.this.refreshButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == saveButton1) {
                    Empleados2.this.saveButton1ActionPerformed(evt);
                }
            }
        }// </editor-fold>//GEN-END:initComponents

    

   
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void newButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton1ActionPerformed
        com.udec.modelo.Empleado e = new com.udec.modelo.Empleado();
        entityManager.persist(e);
        list.add(e);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButton1ActionPerformed

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButton1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
         try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<com.udec.modelo.Empleado> merged = new ArrayList<com.udec.modelo.Empleado>(list.size());
            for (com.udec.modelo.Empleado e : list) {
                merged.add(entityManager.merge(e));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bancoIdbancoLabel;
    private java.util.List<com.udec.modelo.Banco> bancoList;
    private javax.persistence.Query bancoQuery;
    private javax.swing.JLabel cargoCargoidLabel;
    private java.util.List<com.udec.modelo.Cargo> cargoList;
    private javax.persistence.Query cargoQuery;
    private javax.swing.JTextField cedulaField;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoLabel;
    private com.udec.vista.DateConverter dateConverter1;
    private com.udec.vista.DoubleConverter doubleConverter1;
    private java.util.List<com.udec.modelo.Empleado> empleadoList;
    private javax.persistence.Query empleadoQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private java.util.List<com.udec.modelo.Empleado> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField numeroCuentaField;
    private javax.swing.JLabel numeroCuentaLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JTextField salarioField;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JButton saveButton1;
    private javax.swing.JLabel tipoLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
   
    
}
